name: 'Barecheck - Code Coverage'
description: 'Sends a message to PR with proper percentage of code coverage'
branding:
  icon: 'check-circle'
  color: 'yellow'
inputs:
  github-token:
    description: Your GitHub secret token
    required: true
  lcov-file:
    description: 'Path where code coverage artifacts located'
    required: true
    default: './coverage/lcov.info'
  head-lcov-file:
    description: 'Code coverage head branch report to compare with'
    required: true
    default: null
outputs:
  percentage:
    description: 'Total Percentage coverage'
  diff:
    description: 'Percantage difference between head branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
