name: 'Barecheck - Code Coverage'
description: 'Sends a message to PR with proper percentage of code coverage'
branding:
  icon: 'check-circle'
  color: 'yellow'
inputs:
  github-token:
    description: Your GitHub secret token
    required: true
  lcov-file:
    description: 'Compare code coverage report'
    required: true
    default: './coverage/lcov.info'
  base-lcov-file:
    description: 'Base code coverage report to generate percentage diff'
    required: true
    default: ''
  minimum-ratio:
    description: 'Minimum code coverage ratio that would to be considered as a difference between based and head commits'
    required: false
    default: ''
  send-summary-comment:
    description: 'Send Github Pull request comment with code coverage summary'
    required: false
    default: '0'
outputs:
  percentage:
    description: 'Total Percentage coverage'
  diff:
    description: 'Percantage difference between head branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
