name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.11.0
        uses: actions/setup-node@v1
        with:
          node-version: v16.11.0

      - name: Install dependencies
        run: yarn

      - name: Run linting checks
        run: yarn lint

      - name: Run formatting checks
        run: yarn format-check

      - name: Install dependencies
        run: yarn test

      - name: Run test coverage
        run: yarn coverage

      # Testing beta of code coverage checks
      # This part can be removed or optimized once barecheck code coverage will be out of beta
      - name: Generate Code Coverage report
        id: code-coverage
        uses: ./
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          barecheck-api-key: ${{ secrets.BARECHECK_API_KEY }}
          lcov-file: "./coverage/lcov.info"
          minimum-ratio: 0
          send-summary-comment: true
          show-annotations: "warning"
          app-name: "Github Action"
